spring:

  datasource:
    url: jdbc:h2:file:./data/telecom_cdr
    username: noleg
    password: root
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

generation:
  count:
    cdr: 100

report:
  directory: report


